### ISSUE TITLE
Non boolean result on "onRewarded"

### ISSUE THREAD

**Issue by 4rombusiness** [OverShifted/GodotTapsell#1]
Great work it was really needed for Godot.
Almost ok but at the end when plugin wants to send successful signal to Godot "java.lang.IllegalArgumentException"  happens.
<img width="916" alt="Screen Shot 2021-08-01 at 8 05 12 PM" src="https://user-images.githubusercontent.com/74930940/127776777-4a355c6c-3601-41cf-a84e-935b0246976d.png">

**Comment by OverShifted** [comment]
I am very happy that I could help some people out there.
I've found the reason for this exception and I will fix it ASAP.
Basically, the problem is this:
![Screenshot_20210802_103338](https://user-images.githubusercontent.com/53635046/127812073-fbe61d6f-ac45-4270-a497-74c9578ce1d8.png)
In Java; a `boolean` is not recognized as an instance of `boolean`. Because `boolean` is not an `Object` type. I should use `Boolean` instead (notice the capital `B`).

**Comment by OverShifted** [comment]
Done :)
