### ISSUE TITLE
Any plan for other types of ads?

### ISSUE THREAD

**Issue by 4rombusiness** [OverShifted/GodotTapsell#2]
Specially banners...

**Comment by OverShifted** [comment]
No (currently).
Mostly because banner ads are the most annoying type of ad in games. So only a few games use it.
But it shouldn't be much harder to implement. (I am currently a student and don't have much time to do so).
So you might want to give it a try.

Just add new methods to [this class](https://github.com/OverShifted/GodotTapsell/blob/main/AndroidStudioProject/GodotTapsell/GodotTapsell/src/main/java/com/overshifted/godottapsell/GodotTapsell.java).
If you put `@UsedByGodot` before a method; That is gonna be exposed to Godot.

Other resources: https://docs.godotengine.org/en/stable/tutorials/plugins/android/android_plugin.html
