### ISSUE TITLE
cant install plugin

### ISSUE THREAD

**Issue by WhiteWolf-Sim** [OverShifted/GodotTapsell#6]
hi 
i use godot 3.5 
and i tested with godot 3.2 to be sure 
and used the description(install part) and tried a few times 
but i get this err :
`could not load plugin : GodotTapsell`
i surfed and saw some topics that maybe help me and i found that the 
`Engine.has_autoload(plugin_name)`wont work for project autoload and its a editor/engine command 
here is the links  : 

[https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#doc-making-plugins-autoload](url)
[https://godotengine.org/qa/95097/engine-has_singleton-engine-get_singleton-behaving-expected](url)
[https://github.com/godotengine/godot-proposals/issues/1649](url)

godotdoc says : 
>Godot won't make an AutoLoad a "true" singleton as per the singleton design pattern. It may still be instanced more than once by >the user if desired.
>Tip
>If you're creating an autoload as part of an editor plugin, consider [registering it automatically in the Project Settings] 
(https://docs.godotengine.org/en/stable/tutorials/plugins/editor/making_plugins.html#doc-making-plugins-autoload) when the plugin is enabled.

how should i fix the err?

and after that there is a `plugin.init(app,true)` and in this version (godot 3.5 )it seems that won't work  it says it will be removed in godot 4.0 and its better to use _initialize() and gives a nonexistence func err to me 

p.s : ty for making this plugin it seems to be very useful 👍

**Comment by OverShifted** [comment]
Hi. Getting the `could not load plugin : GodotTapsell` error message is expected in the editor because the plugin is only available on the Android build of your project.

Also, `plugin.init` is implemented by the [custom native plugin](https://github.com/OverShifted/GodotTapsell/blob/main/AndroidStudioProject/GodotTapsell/GodotTapsell/src/main/java/com/overshifted/godottapsell/GodotTapsell.java#L68), so it is not a part of the Godot engine and wont be removed.

**Comment by WhiteWolf-Sim** [comment]
ty
